# Generated by Django 4.2.7 on 2023-11-25 19:26

from django.db import migrations

def insert_initial_data(apps, schema_editor):
    Course = apps.get_model('ClassTracker', 'Course')
    Skill = apps.get_model('ClassTracker', 'Skill')
    CourseSkill = apps.get_model('ClassTracker', 'CourseSkill')
    UserCourse = apps.get_model('ClassTracker', 'UserCourse')

    # Insert courses
    Course.objects.bulk_create([
        Course(
            id=1,
            course_number="SDEV 240",
            name="Software Development Using C#",
            description="Provides an understanding of fundamental and advanced concepts of the C# programming language. The emphasis will be on creating industry standard programs using current programming design software. Students will learn basic programming concepts such as sequence, iteration and decision structures; variables and constants; and functions and advanced concepts such as searches, sorts, collections, dictionaries, arrays, and linked lists. Classes, inheritance, polymorphism, connecting to databases, and multiform projects will also be utilized. Students will apply these skills in a hands-on environment. Students will practice skills such as team building, work ethic, communications, documentation, and adaptability."
        ),
        Course(
            id=2,
            course_number="SVAD 150",
            name="Cloud Foundations",
            description="Cloud Foundations is intended for students who seek a general understanding of cloud computing concepts, independent of specific technical roles. It provides a detailed overview of cloud concepts, core services, security, architecture, pricing, and support."
        ),
    ])

    # Insert skills
    Skill.objects.bulk_create([
        Skill(pk=2, skill_keyword="C#"),
        Skill(pk=3, skill_keyword="Programming"),
        Skill(pk=4, skill_keyword="Software design"),
        Skill(pk=5, skill_keyword="Data structures"),
        Skill(pk=6, skill_keyword="C# programming"),
        Skill(pk=7, skill_keyword="Object-oriented programming"),
        Skill(pk=8, skill_keyword="Algorithms"),
        Skill(pk=9, skill_keyword="Software Design"),
        Skill(pk=10, skill_keyword="Databases"),
        Skill(pk=11, skill_keyword="Data Structures"),
        Skill(pk=12, skill_keyword="Programming language"),
        Skill(pk=13, skill_keyword="Software development"),
        Skill(pk=14, skill_keyword="cloud computing"),
        Skill(pk=15, skill_keyword="cloud concepts"),
        Skill(pk=16, skill_keyword="core services"),
        Skill(pk=17, skill_keyword="security"),
        Skill(pk=18, skill_keyword="architecture"),
    ])

    # Insert CourseSkills
    skill_2 = Skill.objects.get(pk=2)
    skill_3 = Skill.objects.get(pk=3)
    skill_4 = Skill.objects.get(pk=4)
    skill_5 = Skill.objects.get(pk=5)
    skill_6 = Skill.objects.get(pk=6)
    skill_7 = Skill.objects.get(pk=7)
    skill_8 = Skill.objects.get(pk=8)
    skill_9 = Skill.objects.get(pk=9)
    skill_10 = Skill.objects.get(pk=10)
    skill_11 = Skill.objects.get(pk=11)
    skill_12 = Skill.objects.get(pk=12)
    skill_13 = Skill.objects.get(pk=13)
    skill_14 = Skill.objects.get(pk=14)
    skill_15 = Skill.objects.get(pk=15)
    skill_16 = Skill.objects.get(pk=16)
    skill_17 = Skill.objects.get(pk=17)
    skill_18 = Skill.objects.get(pk=18)

    CourseSkill.objects.bulk_create([
        CourseSkill(course_number_id=1, skills_id=skill_2),
        CourseSkill(course_number_id=1, skills_id=skill_3),
        CourseSkill(course_number_id=1, skills_id=skill_4),
        CourseSkill(course_number_id=1, skills_id=skill_5),
        CourseSkill(course_number_id=1, skills_id=skill_6),
        CourseSkill(course_number_id=1, skills_id=skill_7),
        CourseSkill(course_number_id=1, skills_id=skill_8),
        CourseSkill(course_number_id=1, skills_id=skill_9),
        CourseSkill(course_number_id=1, skills_id=skill_10),
        CourseSkill(course_number_id=1, skills_id=skill_11),
        CourseSkill(course_number_id=1, skills_id=skill_12),
        CourseSkill(course_number_id=1, skills_id=skill_13),
        CourseSkill(course_number_id=2, skills_id=skill_14),
        CourseSkill(course_number_id=2, skills_id=skill_15),
        CourseSkill(course_number_id=2, skills_id=skill_16),
        CourseSkill(course_number_id=2, skills_id=skill_17),
        CourseSkill(course_number_id=2, skills_id=skill_18),
    ])

    # Insert UserCourses
    UserCourse.objects.bulk_create([
        UserCourse(user_id=1, course_id=1),
        UserCourse(user_id=1, course_id=2),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('ClassTracker', '0001_initial'),
        ('UserInfo', '0005_auto_20231125_1424'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data),
    ]
