# Generated by Django 3.2.23 on 2023-12-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassTracker', '0002_auto_20231125_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=10),
        ),
    ]
