# Generated by Django 4.2.7 on 2023-11-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='page',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
