# Generated by Django 4.2.7 on 2023-11-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_id',
            field=models.IntegerField(),
        ),
    ]
