# Generated by Django 4.2.7 on 2023-11-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_remove_userinformation_id_userinformation_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
