# Generated by Django 4.2.7 on 2023-11-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0003_remove_userinformation_user_id_userinformation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
