# Generated by Django 3.2.23 on 2023-11-29 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0005_auto_20231125_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='tagline',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Tagline must be at least 10 characters long.')]),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='zip_code',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Zip code must be in the format XXXXX or XXXXX-XXXX', regex='^\\d{5}(?:-\\d{4})?$')]),
        ),
    ]
