# Generated by Django 3.2.23 on 2023-12-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhistory',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
