# Generated by Django 3.2.23 on 2023-12-05 20:24
from datetime import datetime
from django.db import models, migrations

update_sql = '''
UPDATE ResumeBuilder_education
SET school_start_date = DATE(school_start_date),
    school_end_date = DATE(school_end_date);
'''

class Migration(migrations.Migration):

    dependencies = [
        ('ResumeBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_start_date',
            field=models.DateField(),
        ),

        migrations.RunSQL(update_sql),
    ]