# Generated by Django 4.2.7 on 2023-11-25 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0005_auto_20231125_1424'),
        ('ResumeBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserInfo.userinformation'),
            preserve_default=False,
        ),
    ]
