# Generated by Django 3.2.23 on 2023-12-08 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeBuilder', '0002_auto_20231205_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='zip',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Zip code must be in the format XXXXX or XXXXX-XXXX', regex='^\\d{5}(?:-\\d{4})?$')]),
        ),
    ]
