# Generated by Django 4.2.7 on 2023-11-25 20:58

from django.db import migrations, models

def insert_initial_data(apps, schema_editor):
    WorkHistory = apps.get_model('ResumeBuilder', 'WorkHistory')
    User = apps.get_model('UserInfo', 'UserInformation')
    
    user = User.objects.get(pk=1)
    
    WorkHistory.objects.create(
        id=1,
        company_name="Lou's Tavern",
        work_address="123 E. Main Street",
        city="Anytown",
        state="IN",
        zip="47429",
        phone="8129751483",
        start_date="2020-11-25T11:11:11Z",
        end_date="2023-11-25T20:56:06Z",
        user=user
    )

class Migration(migrations.Migration):

    dependencies = [
        ('ResumeBuilder', '0002_workhistory_user'),
        ('UserInfo', '0005_auto_20231125_1424')
    ]

    operations = [
        migrations.RunPython(insert_initial_data),
    ]
