# Generated by Django 3.2.23 on 2023-11-27 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClassTracker', '0002_auto_20231125_1426'),
        ('UserInfo', '0005_auto_20231125_1424'),
        ('ResumeBuilder', '0003_auto_20231125_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulateKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassTracker.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_state', models.CharField(max_length=100)),
                ('school_city', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('school_start_date', models.DateTimeField()),
                ('school_end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInfo.userinformation')),
            ],
        ),
    ]
