# Generated by Django 3.2.23 on 2023-11-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserInfo', '0005_auto_20231125_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.TextField()),
                ('salary_range', models.TextField()),
                ('description', models.TextField()),
                ('hyperlink', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInfo.userinformation')),
            ],
        ),
    ]
