# Generated by Django 4.2.7 on 2023-11-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobSearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user_id',
            new_name='user',
        ),
    ]
